const trafficData = [
    { date: "03/10/22", number: 351, type: "2R", direction: "vers Entrée Fac" },
    { date: "03/10/22", number: 140, type: "2R", direction: "vers Sortie Fac" },
    { date: "03/10/22", number: 90, type: "2R", direction: "vers Talence" },
    { date: "03/10/22", number: 58, type: "PL", direction: "vers Entrée Fac" },
    { date: "03/10/22", number: 26, type: "PL", direction: "vers Sortie Fac" },
    { date: "03/10/22", number: 1, type: "PL", direction: "vers Talence" },
    {
        date: "03/10/22",
        number: 6038,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    {
        date: "03/10/22",
        number: 4206,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "03/10/22", number: 985, type: "VL", direction: "vers Talence" },
    { date: "04/10/22", number: 91, type: "2R", direction: "vers BEC" },
    { date: "04/10/22", number: 73, type: "2R", direction: "vers COSEC" },
    {
        date: "04/10/22",
        number: 1404,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "04/10/22", number: 198, type: "2R", direction: "vers Rocade" },
    { date: "04/10/22", number: 868, type: "2R", direction: "vers Sortie Fac" },
    { date: "04/10/22", number: 168, type: "2R", direction: "vers Talence" },
    { date: "04/10/22", number: 51, type: "PL", direction: "vers BEC" },
    { date: "04/10/22", number: 50, type: "PL", direction: "vers COSEC" },
    { date: "04/10/22", number: 411, type: "PL", direction: "vers Entrée Fac" },
    { date: "04/10/22", number: 19, type: "PL", direction: "vers Rocade" },
    { date: "04/10/22", number: 90, type: "PL", direction: "vers Sortie Fac" },
    { date: "04/10/22", number: 10, type: "PL", direction: "vers Talence" },
    { date: "04/10/22", number: 1459, type: "VL", direction: "vers BEC" },
    { date: "04/10/22", number: 955, type: "VL", direction: "vers COSEC" },
    {
        date: "04/10/22",
        number: 20880,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "04/10/22", number: 3158, type: "VL", direction: "vers Rocade" },
    {
        date: "04/10/22",
        number: 10654,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "04/10/22", number: 2203, type: "VL", direction: "vers Talence" },
    { date: "05/10/22", number: 101, type: "2R", direction: "vers BEC" },
    { date: "05/10/22", number: 76, type: "2R", direction: "vers COSEC" },
    {
        date: "05/10/22",
        number: 1974,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "05/10/22", number: 256, type: "2R", direction: "vers Rocade" },
    {
        date: "05/10/22",
        number: 1016,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "05/10/22", number: 171, type: "2R", direction: "vers Talence" },
    { date: "05/10/22", number: 72, type: "PL", direction: "vers BEC" },
    { date: "05/10/22", number: 72, type: "PL", direction: "vers COSEC" },
    { date: "05/10/22", number: 498, type: "PL", direction: "vers Entrée Fac" },
    { date: "05/10/22", number: 19, type: "PL", direction: "vers Rocade" },
    { date: "05/10/22", number: 96, type: "PL", direction: "vers Sortie Fac" },
    { date: "05/10/22", number: 11, type: "PL", direction: "vers Talence" },
    { date: "05/10/22", number: 1902, type: "VL", direction: "vers BEC" },
    { date: "05/10/22", number: 1193, type: "VL", direction: "vers COSEC" },
    {
        date: "05/10/22",
        number: 23716,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "05/10/22", number: 3988, type: "VL", direction: "vers Rocade" },
    {
        date: "05/10/22",
        number: 10594,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "05/10/22", number: 1919, type: "VL", direction: "vers Talence" },
    { date: "06/10/22", number: 69, type: "2R", direction: "vers BEC" },
    { date: "06/10/22", number: 22, type: "2R", direction: "vers COSEC" },
    {
        date: "06/10/22",
        number: 1937,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "06/10/22", number: 257, type: "2R", direction: "vers Rocade" },
    {
        date: "06/10/22",
        number: 1012,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "06/10/22", number: 135, type: "2R", direction: "vers Talence" },
    {
        date: "06/10/22",
        number: 32,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    { date: "06/10/22", number: 103, type: "PL", direction: "vers BEC" },
    { date: "06/10/22", number: 736, type: "PL", direction: "vers COSEC" },
    { date: "06/10/22", number: 481, type: "PL", direction: "vers Entrée Fac" },
    { date: "06/10/22", number: 22, type: "PL", direction: "vers Rocade" },
    { date: "06/10/22", number: 83, type: "PL", direction: "vers Sortie Fac" },
    { date: "06/10/22", number: 10, type: "PL", direction: "vers Talence" },
    {
        date: "06/10/22",
        number: 3,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "06/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "06/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    { date: "06/10/22", number: 1786, type: "VL", direction: "vers BEC" },
    { date: "06/10/22", number: 627, type: "VL", direction: "vers COSEC" },
    {
        date: "06/10/22",
        number: 24262,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "06/10/22", number: 4241, type: "VL", direction: "vers Rocade" },
    {
        date: "06/10/22",
        number: 11205,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "06/10/22", number: 1982, type: "VL", direction: "vers Talence" },
    {
        date: "06/10/22",
        number: 161,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "06/10/22",
        number: 2,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "06/10/22",
        number: 2,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "07/10/22",
        number: 137,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "07/10/22", number: 7, type: "2R", direction: "vers BEC" },
    { date: "07/10/22", number: 7, type: "2R", direction: "vers COSEC" },
    { date: "07/10/22", number: 198, type: "2R", direction: "vers CROUS" },
    {
        date: "07/10/22",
        number: 271,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "07/10/22",
        number: 2019,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "07/10/22", number: 238, type: "2R", direction: "vers Rocade" },
    { date: "07/10/22", number: 925, type: "2R", direction: "vers Sortie Fac" },
    { date: "07/10/22", number: 153, type: "2R", direction: "vers Talence" },
    {
        date: "07/10/22",
        number: 92,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "07/10/22",
        number: 148,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "07/10/22",
        number: 4,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "07/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "07/10/22",
        number: 12,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "07/10/22", number: 19, type: "PL", direction: "vers BEC" },
    { date: "07/10/22", number: 168, type: "PL", direction: "vers COSEC" },
    { date: "07/10/22", number: 22, type: "PL", direction: "vers CROUS" },
    {
        date: "07/10/22",
        number: 15,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "07/10/22", number: 474, type: "PL", direction: "vers Entrée Fac" },
    { date: "07/10/22", number: 14, type: "PL", direction: "vers Rocade" },
    { date: "07/10/22", number: 100, type: "PL", direction: "vers Sortie Fac" },
    { date: "07/10/22", number: 7, type: "PL", direction: "vers Talence" },
    {
        date: "07/10/22",
        number: 2,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "07/10/22",
        number: 4,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "07/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "07/10/22",
        number: 959,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "07/10/22", number: 2753, type: "VL", direction: "vers BEC" },
    { date: "07/10/22", number: 148, type: "VL", direction: "vers COSEC" },
    { date: "07/10/22", number: 2401, type: "VL", direction: "vers CROUS" },
    {
        date: "07/10/22",
        number: 3798,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "07/10/22",
        number: 24377,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "07/10/22", number: 4343, type: "VL", direction: "vers Rocade" },
    {
        date: "07/10/22",
        number: 10770,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "07/10/22", number: 2047, type: "VL", direction: "vers Talence" },
    {
        date: "07/10/22",
        number: 404,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "07/10/22",
        number: 911,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "07/10/22",
        number: 6,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "07/10/22",
        number: 29,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "08/10/22",
        number: 101,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "08/10/22", number: 31, type: "2R", direction: "vers BEC" },
    { date: "08/10/22", number: 11, type: "2R", direction: "vers COSEC" },
    { date: "08/10/22", number: 141, type: "2R", direction: "vers CROUS" },
    {
        date: "08/10/22",
        number: 123,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    { date: "08/10/22", number: 483, type: "2R", direction: "vers Entrée Fac" },
    { date: "08/10/22", number: 118, type: "2R", direction: "vers Rocade" },
    { date: "08/10/22", number: 194, type: "2R", direction: "vers Sortie Fac" },
    { date: "08/10/22", number: 71, type: "2R", direction: "vers Talence" },
    {
        date: "08/10/22",
        number: 16,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "08/10/22",
        number: 68,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    { date: "08/10/22", number: 4, type: "PL", direction: "Vers bibliothéque" },
    { date: "08/10/22", number: 64, type: "PL", direction: "vers BEC" },
    { date: "08/10/22", number: 424, type: "PL", direction: "vers COSEC" },
    { date: "08/10/22", number: 20, type: "PL", direction: "vers CROUS" },
    {
        date: "08/10/22",
        number: 13,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "08/10/22", number: 260, type: "PL", direction: "vers Entrée Fac" },
    { date: "08/10/22", number: 5, type: "PL", direction: "vers Rocade" },
    { date: "08/10/22", number: 19, type: "PL", direction: "vers Sortie Fac" },
    { date: "08/10/22", number: 1, type: "PL", direction: "vers Talence" },
    {
        date: "08/10/22",
        number: 2,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "08/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "08/10/22",
        number: 669,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "08/10/22", number: 975, type: "VL", direction: "vers BEC" },
    { date: "08/10/22", number: 348, type: "VL", direction: "vers COSEC" },
    { date: "08/10/22", number: 2259, type: "VL", direction: "vers CROUS" },
    {
        date: "08/10/22",
        number: 1915,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "08/10/22",
        number: 13977,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "08/10/22", number: 1802, type: "VL", direction: "vers Rocade" },
    {
        date: "08/10/22",
        number: 6222,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "08/10/22", number: 940, type: "VL", direction: "vers Talence" },
    {
        date: "08/10/22",
        number: 151,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "08/10/22",
        number: 697,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "09/10/22",
        number: 74,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "09/10/22", number: 23, type: "2R", direction: "vers BEC" },
    { date: "09/10/22", number: 8, type: "2R", direction: "vers COSEC" },
    { date: "09/10/22", number: 175, type: "2R", direction: "vers CROUS" },
    {
        date: "09/10/22",
        number: 114,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    { date: "09/10/22", number: 422, type: "2R", direction: "vers Entrée Fac" },
    { date: "09/10/22", number: 92, type: "2R", direction: "vers Rocade" },
    { date: "09/10/22", number: 160, type: "2R", direction: "vers Sortie Fac" },
    { date: "09/10/22", number: 62, type: "2R", direction: "vers Talence" },
    {
        date: "09/10/22",
        number: 35,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "09/10/22",
        number: 68,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    { date: "09/10/22", number: 3, type: "PL", direction: "Vers bibliothéque" },
    { date: "09/10/22", number: 18, type: "PL", direction: "vers BEC" },
    { date: "09/10/22", number: 184, type: "PL", direction: "vers COSEC" },
    { date: "09/10/22", number: 11, type: "PL", direction: "vers CROUS" },
    {
        date: "09/10/22",
        number: 1,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "09/10/22", number: 148, type: "PL", direction: "vers Entrée Fac" },
    { date: "09/10/22", number: 16, type: "PL", direction: "vers Rocade" },
    { date: "09/10/22", number: 30, type: "PL", direction: "vers Sortie Fac" },
    {
        date: "09/10/22",
        number: 1,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "09/10/22",
        number: 1,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "09/10/22",
        number: 582,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "09/10/22", number: 854, type: "VL", direction: "vers BEC" },
    { date: "09/10/22", number: 435, type: "VL", direction: "vers COSEC" },
    { date: "09/10/22", number: 2673, type: "VL", direction: "vers CROUS" },
    {
        date: "09/10/22",
        number: 1922,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "09/10/22",
        number: 12990,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "09/10/22", number: 1568, type: "VL", direction: "vers Rocade" },
    {
        date: "09/10/22",
        number: 6018,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "09/10/22", number: 788, type: "VL", direction: "vers Talence" },
    {
        date: "09/10/22",
        number: 202,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "09/10/22",
        number: 590,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "09/10/22",
        number: 1,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "09/10/22",
        number: 2,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "10/10/22",
        number: 246,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "10/10/22", number: 85, type: "2R", direction: "vers BEC" },
    { date: "10/10/22", number: 41, type: "2R", direction: "vers COSEC" },
    { date: "10/10/22", number: 294, type: "2R", direction: "vers CROUS" },
    {
        date: "10/10/22",
        number: 278,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "10/10/22",
        number: 1188,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "10/10/22", number: 152, type: "2R", direction: "vers Rocade" },
    { date: "10/10/22", number: 723, type: "2R", direction: "vers Sortie Fac" },
    { date: "10/10/22", number: 106, type: "2R", direction: "vers Talence" },
    {
        date: "10/10/22",
        number: 78,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "10/10/22",
        number: 202,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "10/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "10/10/22",
        number: 2,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "10/10/22",
        number: 30,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "10/10/22", number: 82, type: "PL", direction: "vers BEC" },
    { date: "10/10/22", number: 502, type: "PL", direction: "vers COSEC" },
    { date: "10/10/22", number: 99, type: "PL", direction: "vers CROUS" },
    {
        date: "10/10/22",
        number: 73,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "10/10/22", number: 507, type: "PL", direction: "vers Entrée Fac" },
    { date: "10/10/22", number: 20, type: "PL", direction: "vers Rocade" },
    { date: "10/10/22", number: 119, type: "PL", direction: "vers Sortie Fac" },
    { date: "10/10/22", number: 12, type: "PL", direction: "vers Talence" },
    {
        date: "10/10/22",
        number: 3,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "10/10/22",
        number: 17,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "10/10/22",
        number: 1473,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "10/10/22", number: 2652, type: "VL", direction: "vers BEC" },
    { date: "10/10/22", number: 1151, type: "VL", direction: "vers COSEC" },
    { date: "10/10/22", number: 4083, type: "VL", direction: "vers CROUS" },
    {
        date: "10/10/22",
        number: 4231,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "10/10/22",
        number: 22209,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "10/10/22", number: 2699, type: "VL", direction: "vers Rocade" },
    {
        date: "10/10/22",
        number: 14410,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "10/10/22", number: 1892, type: "VL", direction: "vers Talence" },
    {
        date: "10/10/22",
        number: 435,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "10/10/22",
        number: 1392,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "10/10/22",
        number: 16,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "10/10/22",
        number: 38,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "11/10/22",
        number: 189,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "11/10/22", number: 75, type: "2R", direction: "vers BEC" },
    { date: "11/10/22", number: 77, type: "2R", direction: "vers COSEC" },
    { date: "11/10/22", number: 244, type: "2R", direction: "vers CROUS" },
    {
        date: "11/10/22",
        number: 223,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "11/10/22",
        number: 1041,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "11/10/22", number: 142, type: "2R", direction: "vers Rocade" },
    { date: "11/10/22", number: 821, type: "2R", direction: "vers Sortie Fac" },
    { date: "11/10/22", number: 81, type: "2R", direction: "vers Talence" },
    {
        date: "11/10/22",
        number: 59,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "11/10/22",
        number: 157,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "11/10/22",
        number: 2,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "11/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "11/10/22",
        number: 30,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "11/10/22", number: 78, type: "PL", direction: "vers BEC" },
    { date: "11/10/22", number: 67, type: "PL", direction: "vers COSEC" },
    { date: "11/10/22", number: 80, type: "PL", direction: "vers CROUS" },
    {
        date: "11/10/22",
        number: 50,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "11/10/22", number: 590, type: "PL", direction: "vers Entrée Fac" },
    { date: "11/10/22", number: 20, type: "PL", direction: "vers Rocade" },
    { date: "11/10/22", number: 158, type: "PL", direction: "vers Sortie Fac" },
    { date: "11/10/22", number: 16, type: "PL", direction: "vers Talence" },
    {
        date: "11/10/22",
        number: 2,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "11/10/22",
        number: 11,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "11/10/22",
        number: 6,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "11/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "11/10/22",
        number: 1669,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "11/10/22", number: 2989, type: "VL", direction: "vers BEC" },
    { date: "11/10/22", number: 1580, type: "VL", direction: "vers COSEC" },
    { date: "11/10/22", number: 4012, type: "VL", direction: "vers CROUS" },
    {
        date: "11/10/22",
        number: 4429,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "11/10/22",
        number: 23261,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "11/10/22", number: 2661, type: "VL", direction: "vers Rocade" },
    {
        date: "11/10/22",
        number: 16126,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "11/10/22", number: 2198, type: "VL", direction: "vers Talence" },
    {
        date: "11/10/22",
        number: 481,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "11/10/22",
        number: 1491,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "11/10/22",
        number: 17,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "11/10/22",
        number: 31,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "12/10/22",
        number: 228,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "12/10/22", number: 94, type: "2R", direction: "vers BEC" },
    { date: "12/10/22", number: 81, type: "2R", direction: "vers COSEC" },
    { date: "12/10/22", number: 330, type: "2R", direction: "vers CROUS" },
    {
        date: "12/10/22",
        number: 290,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "12/10/22",
        number: 1493,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "12/10/22", number: 184, type: "2R", direction: "vers Rocade" },
    {
        date: "12/10/22",
        number: 1236,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "12/10/22", number: 106, type: "2R", direction: "vers Talence" },
    {
        date: "12/10/22",
        number: 77,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "12/10/22",
        number: 195,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "12/10/22",
        number: 3,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "12/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "12/10/22",
        number: 20,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "12/10/22", number: 18, type: "PL", direction: "vers BEC" },
    { date: "12/10/22", number: 21, type: "PL", direction: "vers COSEC" },
    { date: "12/10/22", number: 78, type: "PL", direction: "vers CROUS" },
    {
        date: "12/10/22",
        number: 53,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "12/10/22", number: 712, type: "PL", direction: "vers Entrée Fac" },
    { date: "12/10/22", number: 26, type: "PL", direction: "vers Rocade" },
    { date: "12/10/22", number: 271, type: "PL", direction: "vers Sortie Fac" },
    { date: "12/10/22", number: 11, type: "PL", direction: "vers Talence" },
    {
        date: "12/10/22",
        number: 3,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "12/10/22",
        number: 12,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "12/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "12/10/22",
        number: 2,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "12/10/22",
        number: 1451,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "12/10/22", number: 2761, type: "VL", direction: "vers BEC" },
    { date: "12/10/22", number: 1491, type: "VL", direction: "vers COSEC" },
    { date: "12/10/22", number: 4099, type: "VL", direction: "vers CROUS" },
    {
        date: "12/10/22",
        number: 4358,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "12/10/22",
        number: 23405,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "12/10/22", number: 2514, type: "VL", direction: "vers Rocade" },
    {
        date: "12/10/22",
        number: 16628,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "12/10/22", number: 1891, type: "VL", direction: "vers Talence" },
    {
        date: "12/10/22",
        number: 420,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "12/10/22",
        number: 1288,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "12/10/22",
        number: 11,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "12/10/22",
        number: 29,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "13/10/22",
        number: 219,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "13/10/22", number: 79, type: "2R", direction: "vers BEC" },
    { date: "13/10/22", number: 93, type: "2R", direction: "vers COSEC" },
    { date: "13/10/22", number: 307, type: "2R", direction: "vers CROUS" },
    {
        date: "13/10/22",
        number: 258,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "13/10/22",
        number: 1876,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "13/10/22", number: 189, type: "2R", direction: "vers Rocade" },
    {
        date: "13/10/22",
        number: 1425,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "13/10/22", number: 105, type: "2R", direction: "vers Talence" },
    {
        date: "13/10/22",
        number: 76,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "13/10/22",
        number: 182,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "13/10/22",
        number: 2,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "13/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "13/10/22",
        number: 23,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "13/10/22", number: 16, type: "PL", direction: "vers BEC" },
    { date: "13/10/22", number: 11, type: "PL", direction: "vers COSEC" },
    { date: "13/10/22", number: 95, type: "PL", direction: "vers CROUS" },
    {
        date: "13/10/22",
        number: 56,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "13/10/22", number: 693, type: "PL", direction: "vers Entrée Fac" },
    { date: "13/10/22", number: 20, type: "PL", direction: "vers Rocade" },
    { date: "13/10/22", number: 275, type: "PL", direction: "vers Sortie Fac" },
    { date: "13/10/22", number: 6, type: "PL", direction: "vers Talence" },
    {
        date: "13/10/22",
        number: 4,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "13/10/22",
        number: 17,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "13/10/22",
        number: 3,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "13/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "13/10/22",
        number: 1499,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "13/10/22", number: 2118, type: "VL", direction: "vers BEC" },
    { date: "13/10/22", number: 1375, type: "VL", direction: "vers COSEC" },
    { date: "13/10/22", number: 3958, type: "VL", direction: "vers CROUS" },
    {
        date: "13/10/22",
        number: 4251,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "13/10/22",
        number: 24334,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "13/10/22", number: 3307, type: "VL", direction: "vers Rocade" },
    {
        date: "13/10/22",
        number: 16885,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "13/10/22", number: 1919, type: "VL", direction: "vers Talence" },
    {
        date: "13/10/22",
        number: 439,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "13/10/22",
        number: 1348,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "13/10/22",
        number: 15,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "13/10/22",
        number: 44,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "14/10/22",
        number: 204,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "14/10/22", number: 65, type: "2R", direction: "vers BEC" },
    { date: "14/10/22", number: 69, type: "2R", direction: "vers COSEC" },
    { date: "14/10/22", number: 271, type: "2R", direction: "vers CROUS" },
    {
        date: "14/10/22",
        number: 229,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "14/10/22",
        number: 1782,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "14/10/22", number: 183, type: "2R", direction: "vers Rocade" },
    {
        date: "14/10/22",
        number: 1297,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "14/10/22", number: 108, type: "2R", direction: "vers Talence" },
    {
        date: "14/10/22",
        number: 68,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "14/10/22",
        number: 148,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "14/10/22",
        number: 3,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "14/10/22",
        number: 21,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "14/10/22", number: 68, type: "PL", direction: "vers BEC" },
    { date: "14/10/22", number: 65, type: "PL", direction: "vers COSEC" },
    { date: "14/10/22", number: 82, type: "PL", direction: "vers CROUS" },
    {
        date: "14/10/22",
        number: 58,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "14/10/22", number: 627, type: "PL", direction: "vers Entrée Fac" },
    { date: "14/10/22", number: 20, type: "PL", direction: "vers Rocade" },
    { date: "14/10/22", number: 161, type: "PL", direction: "vers Sortie Fac" },
    { date: "14/10/22", number: 6, type: "PL", direction: "vers Talence" },
    {
        date: "14/10/22",
        number: 6,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "14/10/22",
        number: 7,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "14/10/22",
        number: 6,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "14/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "14/10/22",
        number: 1462,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "14/10/22", number: 1782, type: "VL", direction: "vers BEC" },
    { date: "14/10/22", number: 1115, type: "VL", direction: "vers COSEC" },
    { date: "14/10/22", number: 4015, type: "VL", direction: "vers CROUS" },
    {
        date: "14/10/22",
        number: 4573,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "14/10/22",
        number: 24240,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "14/10/22", number: 4048, type: "VL", direction: "vers Rocade" },
    {
        date: "14/10/22",
        number: 16652,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "14/10/22", number: 1867, type: "VL", direction: "vers Talence" },
    {
        date: "14/10/22",
        number: 423,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "14/10/22",
        number: 1255,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "14/10/22",
        number: 17,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "14/10/22",
        number: 27,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "15/10/22",
        number: 22,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "15/10/22", number: 41, type: "2R", direction: "vers BEC" },
    { date: "15/10/22", number: 41, type: "2R", direction: "vers COSEC" },
    { date: "15/10/22", number: 131, type: "2R", direction: "vers CROUS" },
    {
        date: "15/10/22",
        number: 98,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    { date: "15/10/22", number: 584, type: "2R", direction: "vers Entrée Fac" },
    { date: "15/10/22", number: 101, type: "2R", direction: "vers Rocade" },
    { date: "15/10/22", number: 484, type: "2R", direction: "vers Sortie Fac" },
    { date: "15/10/22", number: 67, type: "2R", direction: "vers Talence" },
    {
        date: "15/10/22",
        number: 15,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "15/10/22",
        number: 13,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    { date: "15/10/22", number: 1, type: "PL", direction: "Vers bibliothéque" },
    { date: "15/10/22", number: 47, type: "PL", direction: "vers BEC" },
    { date: "15/10/22", number: 51, type: "PL", direction: "vers COSEC" },
    { date: "15/10/22", number: 17, type: "PL", direction: "vers CROUS" },
    {
        date: "15/10/22",
        number: 14,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "15/10/22", number: 329, type: "PL", direction: "vers Entrée Fac" },
    { date: "15/10/22", number: 4, type: "PL", direction: "vers Rocade" },
    { date: "15/10/22", number: 35, type: "PL", direction: "vers Sortie Fac" },
    { date: "15/10/22", number: 2, type: "PL", direction: "vers Talence" },
    {
        date: "15/10/22",
        number: 1,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "15/10/22",
        number: 187,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "15/10/22", number: 1086, type: "VL", direction: "vers BEC" },
    { date: "15/10/22", number: 766, type: "VL", direction: "vers COSEC" },
    { date: "15/10/22", number: 2389, type: "VL", direction: "vers CROUS" },
    {
        date: "15/10/22",
        number: 2070,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "15/10/22",
        number: 14274,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "15/10/22", number: 1837, type: "VL", direction: "vers Rocade" },
    {
        date: "15/10/22",
        number: 11436,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "15/10/22", number: 922, type: "VL", direction: "vers Talence" },
    {
        date: "15/10/22",
        number: 126,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "15/10/22",
        number: 159,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "15/10/22",
        number: 3,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "16/10/22",
        number: 37,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "16/10/22", number: 29, type: "2R", direction: "vers BEC" },
    { date: "16/10/22", number: 44, type: "2R", direction: "vers COSEC" },
    { date: "16/10/22", number: 163, type: "2R", direction: "vers CROUS" },
    {
        date: "16/10/22",
        number: 103,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    { date: "16/10/22", number: 415, type: "2R", direction: "vers Entrée Fac" },
    { date: "16/10/22", number: 97, type: "2R", direction: "vers Rocade" },
    { date: "16/10/22", number: 333, type: "2R", direction: "vers Sortie Fac" },
    { date: "16/10/22", number: 69, type: "2R", direction: "vers Talence" },
    {
        date: "16/10/22",
        number: 24,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "16/10/22",
        number: 23,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    { date: "16/10/22", number: 31, type: "PL", direction: "vers BEC" },
    { date: "16/10/22", number: 30, type: "PL", direction: "vers COSEC" },
    { date: "16/10/22", number: 11, type: "PL", direction: "vers CROUS" },
    {
        date: "16/10/22",
        number: 3,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "16/10/22", number: 197, type: "PL", direction: "vers Entrée Fac" },
    { date: "16/10/22", number: 2, type: "PL", direction: "vers Rocade" },
    { date: "16/10/22", number: 43, type: "PL", direction: "vers Sortie Fac" },
    {
        date: "16/10/22",
        number: 172,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "16/10/22", number: 727, type: "VL", direction: "vers BEC" },
    { date: "16/10/22", number: 654, type: "VL", direction: "vers COSEC" },
    { date: "16/10/22", number: 2226, type: "VL", direction: "vers CROUS" },
    {
        date: "16/10/22",
        number: 1582,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "16/10/22",
        number: 11444,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "16/10/22", number: 1513, type: "VL", direction: "vers Rocade" },
    {
        date: "16/10/22",
        number: 10058,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "16/10/22", number: 752, type: "VL", direction: "vers Talence" },
    {
        date: "16/10/22",
        number: 69,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "16/10/22",
        number: 159,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "17/10/22",
        number: 179,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "17/10/22", number: 62, type: "2R", direction: "vers BEC" },
    { date: "17/10/22", number: 58, type: "2R", direction: "vers COSEC" },
    { date: "17/10/22", number: 254, type: "2R", direction: "vers CROUS" },
    {
        date: "17/10/22",
        number: 215,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "17/10/22",
        number: 1292,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "17/10/22", number: 162, type: "2R", direction: "vers Rocade" },
    {
        date: "17/10/22",
        number: 1126,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "17/10/22", number: 86, type: "2R", direction: "vers Talence" },
    {
        date: "17/10/22",
        number: 56,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "17/10/22",
        number: 156,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "17/10/22",
        number: 2,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "17/10/22",
        number: 16,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "17/10/22", number: 68, type: "PL", direction: "vers BEC" },
    { date: "17/10/22", number: 61, type: "PL", direction: "vers COSEC" },
    { date: "17/10/22", number: 88, type: "PL", direction: "vers CROUS" },
    {
        date: "17/10/22",
        number: 64,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "17/10/22", number: 606, type: "PL", direction: "vers Entrée Fac" },
    { date: "17/10/22", number: 17, type: "PL", direction: "vers Rocade" },
    { date: "17/10/22", number: 165, type: "PL", direction: "vers Sortie Fac" },
    { date: "17/10/22", number: 11, type: "PL", direction: "vers Talence" },
    {
        date: "17/10/22",
        number: 1,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "17/10/22",
        number: 5,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "17/10/22",
        number: 3,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "17/10/22",
        number: 1390,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "17/10/22", number: 1608, type: "VL", direction: "vers BEC" },
    { date: "17/10/22", number: 1232, type: "VL", direction: "vers COSEC" },
    { date: "17/10/22", number: 4173, type: "VL", direction: "vers CROUS" },
    {
        date: "17/10/22",
        number: 4032,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "17/10/22",
        number: 23069,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "17/10/22", number: 3732, type: "VL", direction: "vers Rocade" },
    {
        date: "17/10/22",
        number: 15910,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "17/10/22", number: 1887, type: "VL", direction: "vers Talence" },
    {
        date: "17/10/22",
        number: 434,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "17/10/22",
        number: 1230,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "17/10/22",
        number: 12,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "17/10/22",
        number: 30,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "18/10/22",
        number: 256,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "18/10/22", number: 101, type: "2R", direction: "vers BEC" },
    { date: "18/10/22", number: 93, type: "2R", direction: "vers COSEC" },
    { date: "18/10/22", number: 376, type: "2R", direction: "vers CROUS" },
    {
        date: "18/10/22",
        number: 329,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "18/10/22",
        number: 1695,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "18/10/22", number: 241, type: "2R", direction: "vers Rocade" },
    {
        date: "18/10/22",
        number: 1234,
        type: "2R",
        direction: "vers Sortie Fac",
    },
    { date: "18/10/22", number: 20, type: "2R", direction: "vers Talence" },
    {
        date: "18/10/22",
        number: 84,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "18/10/22",
        number: 212,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "18/10/22",
        number: 2,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "18/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "18/10/22",
        number: 23,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "18/10/22", number: 64, type: "PL", direction: "vers BEC" },
    { date: "18/10/22", number: 62, type: "PL", direction: "vers COSEC" },
    { date: "18/10/22", number: 71, type: "PL", direction: "vers CROUS" },
    {
        date: "18/10/22",
        number: 53,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "18/10/22", number: 393, type: "PL", direction: "vers Entrée Fac" },
    { date: "18/10/22", number: 21, type: "PL", direction: "vers Rocade" },
    { date: "18/10/22", number: 129, type: "PL", direction: "vers Sortie Fac" },
    { date: "18/10/22", number: 3, type: "PL", direction: "vers Talence" },
    {
        date: "18/10/22",
        number: 1,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "18/10/22",
        number: 14,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "18/10/22",
        number: 3,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "18/10/22",
        number: 1464,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "18/10/22", number: 1766, type: "VL", direction: "vers BEC" },
    { date: "18/10/22", number: 1221, type: "VL", direction: "vers COSEC" },
    { date: "18/10/22", number: 4113, type: "VL", direction: "vers CROUS" },
    {
        date: "18/10/22",
        number: 4501,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "18/10/22",
        number: 12009,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "18/10/22", number: 3920, type: "VL", direction: "vers Rocade" },
    {
        date: "18/10/22",
        number: 9806,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    { date: "18/10/22", number: 393, type: "VL", direction: "vers Talence" },
    {
        date: "18/10/22",
        number: 494,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "18/10/22",
        number: 1346,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "18/10/22",
        number: 15,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "18/10/22",
        number: 29,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "19/10/22",
        number: 256,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "19/10/22", number: 14, type: "2R", direction: "vers BEC" },
    { date: "19/10/22", number: 15, type: "2R", direction: "vers COSEC" },
    { date: "19/10/22", number: 326, type: "2R", direction: "vers CROUS" },
    {
        date: "19/10/22",
        number: 308,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    {
        date: "19/10/22",
        number: 1120,
        type: "2R",
        direction: "vers Entrée Fac",
    },
    { date: "19/10/22", number: 57, type: "2R", direction: "vers Rocade" },
    { date: "19/10/22", number: 777, type: "2R", direction: "vers Sortie Fac" },
    {
        date: "19/10/22",
        number: 92,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "19/10/22",
        number: 205,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "19/10/22",
        number: 3,
        type: "2R",
        direction: "vers parking cafeteria",
    },
    {
        date: "19/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    {
        date: "19/10/22",
        number: 21,
        type: "PL",
        direction: "Vers bibliothéque",
    },
    { date: "19/10/22", number: 20, type: "PL", direction: "vers BEC" },
    { date: "19/10/22", number: 18, type: "PL", direction: "vers COSEC" },
    { date: "19/10/22", number: 83, type: "PL", direction: "vers CROUS" },
    {
        date: "19/10/22",
        number: 65,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "19/10/22", number: 89, type: "PL", direction: "vers Entrée Fac" },
    { date: "19/10/22", number: 6, type: "PL", direction: "vers Rocade" },
    { date: "19/10/22", number: 53, type: "PL", direction: "vers Sortie Fac" },
    {
        date: "19/10/22",
        number: 4,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "19/10/22",
        number: 11,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "19/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "19/10/22",
        number: 1,
        type: "PL",
        direction: "vers parking des professeurs",
    },
    {
        date: "19/10/22",
        number: 1376,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "19/10/22", number: 260, type: "VL", direction: "vers BEC" },
    { date: "19/10/22", number: 236, type: "VL", direction: "vers COSEC" },
    { date: "19/10/22", number: 3992, type: "VL", direction: "vers CROUS" },
    {
        date: "19/10/22",
        number: 4266,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    {
        date: "19/10/22",
        number: 2905,
        type: "VL",
        direction: "vers Entrée Fac",
    },
    { date: "19/10/22", number: 879, type: "VL", direction: "vers Rocade" },
    {
        date: "19/10/22",
        number: 2505,
        type: "VL",
        direction: "vers Sortie Fac",
    },
    {
        date: "19/10/22",
        number: 469,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "19/10/22",
        number: 1229,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "19/10/22",
        number: 14,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "19/10/22",
        number: 20,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    {
        date: "20/10/22",
        number: 104,
        type: "2R",
        direction: "Vers bibliothéque",
    },
    { date: "20/10/22", number: 187, type: "2R", direction: "vers CROUS" },
    {
        date: "20/10/22",
        number: 103,
        type: "2R",
        direction: "vers Cours de la Libération",
    },
    { date: "20/10/22", number: 607, type: "2R", direction: "vers Entrée Fac" },
    { date: "20/10/22", number: 206, type: "2R", direction: "vers Sortie Fac" },
    {
        date: "20/10/22",
        number: 85,
        type: "2R",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "20/10/22",
        number: 46,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "20/10/22",
        number: 1,
        type: "2R",
        direction: "vers parking des professeurs",
    },
    { date: "20/10/22", number: 8, type: "PL", direction: "Vers bibliothéque" },
    { date: "20/10/22", number: 66, type: "PL", direction: "vers CROUS" },
    {
        date: "20/10/22",
        number: 35,
        type: "PL",
        direction: "vers Cours de la Libération",
    },
    { date: "20/10/22", number: 12, type: "PL", direction: "vers Entrée Fac" },
    { date: "20/10/22", number: 12, type: "PL", direction: "vers Sortie Fac" },
    {
        date: "20/10/22",
        number: 4,
        type: "PL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "20/10/22",
        number: 7,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "20/10/22",
        number: 3,
        type: "PL",
        direction: "vers parking cafeteria",
    },
    {
        date: "20/10/22",
        number: 590,
        type: "VL",
        direction: "Vers bibliothéque",
    },
    { date: "20/10/22", number: 2556, type: "VL", direction: "vers CROUS" },
    {
        date: "20/10/22",
        number: 1688,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { date: "20/10/22", number: 816, type: "VL", direction: "vers Entrée Fac" },
    { date: "20/10/22", number: 479, type: "VL", direction: "vers Sortie Fac" },
    {
        date: "20/10/22",
        number: 372,
        type: "VL",
        direction: "vers avenue Léon Duguit",
    },
    {
        date: "20/10/22",
        number: 518,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul",
    },
    {
        date: "20/10/22",
        number: 10,
        type: "VL",
        direction: "vers parking cafeteria",
    },
    {
        date: "20/10/22",
        number: 26,
        type: "VL",
        direction: "vers parking des professeurs",
    },
    { date: "21/10/22", number: 43, type: "2R", direction: "vers Entrée Fac" },
    { date: "21/10/22", number: 2, type: "2R", direction: "vers Sortie Fac" },
    { date: "21/10/22", number: 5, type: "PL", direction: "vers Entrée Fac" },
    { date: "21/10/22", number: 5, type: "PL", direction: "vers Sortie Fac" },
    { date: "21/10/22", number: 110, type: "VL", direction: "vers Entrée Fac" },
    { date: "21/10/22", number: 34, type: "VL", direction: "vers Sortie Fac" },
];

export const getAllDirections = () => {
    const directions = trafficData.map((data) => data.direction);
    const setDirections = new Set(directions);
    const uniqueDirections = Array.from(setDirections);
    return uniqueDirections;
};

export const getNumberByDirection = (direction: string) => {
    return trafficData.filter((data) => data.direction === direction);
};

export const getPL = (date: string, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.type === "PL" &&
            data.date === date &&
            data.direction === direction
    )[0]?.number;
};

export const getVL = (date: string, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.date === date &&
            data.type === "VL" &&
            data.direction === direction
    )[0]?.number;
};

export const get2R = (date: string, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.type === "2R" &&
            data.date === date &&
            data.direction === direction
    )[0]?.number;
};

export const removeDuplications = (
    array: {
        date: string;
        numberPL: number;
        numberVL: number;
        number2R: number;
    }[]
) => {
    return array.filter((thing: any, index, self) => {
        return (
            index ===
            self.findIndex((t) => {
                return (
                    t.date === thing.date &&
                    t.numberPL === thing.numberPL &&
                    t.numberVL === thing.numberVL &&
                    t.number2R === thing.number2R
                );
            })
        );
    });
};

export const reduceByDirection = () => {
    const directions = trafficData.map((data) => data.direction);
    const setDirections = new Set(directions);
    const uniqueDirections = Array.from(setDirections);
    const reducedData = uniqueDirections.map((direction: any) => {
        const data = getNumberByDirection(direction);
        return {
            direction: direction,
            values: removeDuplications(
                data.map((data) => {
                    return {
                        date: data.date,
                        numberPL: getPL(data.date, direction),
                        numberVL: getVL(data.date, direction),
                        number2R: get2R(data.date, direction),
                    };
                })
            ),
        };
    });
    return reducedData;
};

export const getDataByDirectionDate = (direction: string) => {
    return reduceByDirection().filter(
        (data) => data.direction === direction
    )[0];
};
