const trafficData = [
    { avg: 1, hour: 0, type: "2R", direction: "Vers bibliothéque" },
    { avg: 10, hour: 0, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 1, type: "2R", direction: "Vers bibliothéque" },
    { avg: 6, hour: 1, type: "VL", direction: "Vers bibliothéque" },
    { avg: 2, hour: 2, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 2, type: "PL", direction: "Vers bibliothéque" },
    { avg: 6, hour: 2, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 3, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 3, type: "PL", direction: "Vers bibliothéque" },
    { avg: 3, hour: 3, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 4, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 4, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 5, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 5, type: "PL", direction: "Vers bibliothéque" },
    { avg: 3, hour: 5, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 6, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 6, type: "PL", direction: "Vers bibliothéque" },
    { avg: 10, hour: 6, type: "VL", direction: "Vers bibliothéque" },
    { avg: 19, hour: 7, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 7, type: "PL", direction: "Vers bibliothéque" },
    { avg: 99, hour: 7, type: "VL", direction: "Vers bibliothéque" },
    { avg: 23, hour: 8, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 8, type: "PL", direction: "Vers bibliothéque" },
    { avg: 126, hour: 8, type: "VL", direction: "Vers bibliothéque" },
    { avg: 18, hour: 9, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 9, type: "PL", direction: "Vers bibliothéque" },
    { avg: 93, hour: 9, type: "VL", direction: "Vers bibliothéque" },
    { avg: 7, hour: 10, type: "2R", direction: "Vers bibliothéque" },
    { avg: 3, hour: 10, type: "PL", direction: "Vers bibliothéque" },
    { avg: 54, hour: 10, type: "VL", direction: "Vers bibliothéque" },
    { avg: 6, hour: 11, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 11, type: "PL", direction: "Vers bibliothéque" },
    { avg: 50, hour: 11, type: "VL", direction: "Vers bibliothéque" },
    { avg: 9, hour: 12, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 12, type: "PL", direction: "Vers bibliothéque" },
    { avg: 77, hour: 12, type: "VL", direction: "Vers bibliothéque" },
    { avg: 15, hour: 13, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 13, type: "PL", direction: "Vers bibliothéque" },
    { avg: 109, hour: 13, type: "VL", direction: "Vers bibliothéque" },
    { avg: 9, hour: 14, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 14, type: "PL", direction: "Vers bibliothéque" },
    { avg: 66, hour: 14, type: "VL", direction: "Vers bibliothéque" },
    { avg: 7, hour: 15, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 15, type: "PL", direction: "Vers bibliothéque" },
    { avg: 75, hour: 15, type: "VL", direction: "Vers bibliothéque" },
    { avg: 13, hour: 16, type: "2R", direction: "Vers bibliothéque" },
    { avg: 2, hour: 16, type: "PL", direction: "Vers bibliothéque" },
    { avg: 109, hour: 16, type: "VL", direction: "Vers bibliothéque" },
    { avg: 16, hour: 17, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 17, type: "PL", direction: "Vers bibliothéque" },
    { avg: 109, hour: 17, type: "VL", direction: "Vers bibliothéque" },
    { avg: 13, hour: 18, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 18, type: "PL", direction: "Vers bibliothéque" },
    { avg: 101, hour: 18, type: "VL", direction: "Vers bibliothéque" },
    { avg: 10, hour: 19, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 19, type: "PL", direction: "Vers bibliothéque" },
    { avg: 65, hour: 19, type: "VL", direction: "Vers bibliothéque" },
    { avg: 7, hour: 20, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 20, type: "PL", direction: "Vers bibliothéque" },
    { avg: 46, hour: 20, type: "VL", direction: "Vers bibliothéque" },
    { avg: 6, hour: 21, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 21, type: "PL", direction: "Vers bibliothéque" },
    { avg: 31, hour: 21, type: "VL", direction: "Vers bibliothéque" },
    { avg: 4, hour: 22, type: "2R", direction: "Vers bibliothéque" },
    { avg: 21, hour: 22, type: "VL", direction: "Vers bibliothéque" },
    { avg: 3, hour: 23, type: "2R", direction: "Vers bibliothéque" },
    { avg: 1, hour: 23, type: "PL", direction: "Vers bibliothéque" },
    { avg: 17, hour: 23, type: "VL", direction: "Vers bibliothéque" },
    { avg: 1, hour: 0, type: "2R", direction: "vers BEC" },
    { avg: 1, hour: 0, type: "PL", direction: "vers BEC" },
    { avg: 14, hour: 0, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 1, type: "2R", direction: "vers BEC" },
    { avg: 6, hour: 1, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 2, type: "2R", direction: "vers BEC" },
    { avg: 1, hour: 2, type: "PL", direction: "vers BEC" },
    { avg: 4, hour: 2, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 3, type: "2R", direction: "vers BEC" },
    { avg: 1, hour: 3, type: "PL", direction: "vers BEC" },
    { avg: 4, hour: 3, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 4, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 4, type: "PL", direction: "vers BEC" },
    { avg: 6, hour: 4, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 5, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 5, type: "PL", direction: "vers BEC" },
    { avg: 8, hour: 5, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 6, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 6, type: "PL", direction: "vers BEC" },
    { avg: 17, hour: 6, type: "VL", direction: "vers BEC" },
    { avg: 4, hour: 7, type: "2R", direction: "vers BEC" },
    { avg: 4, hour: 7, type: "PL", direction: "vers BEC" },
    { avg: 69, hour: 7, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 8, type: "2R", direction: "vers BEC" },
    { avg: 4, hour: 8, type: "PL", direction: "vers BEC" },
    { avg: 110, hour: 8, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 9, type: "2R", direction: "vers BEC" },
    { avg: 5, hour: 9, type: "PL", direction: "vers BEC" },
    { avg: 76, hour: 9, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 10, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 10, type: "PL", direction: "vers BEC" },
    { avg: 75, hour: 10, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 11, type: "2R", direction: "vers BEC" },
    { avg: 4, hour: 11, type: "PL", direction: "vers BEC" },
    { avg: 93, hour: 11, type: "VL", direction: "vers BEC" },
    { avg: 5, hour: 12, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 12, type: "PL", direction: "vers BEC" },
    { avg: 108, hour: 12, type: "VL", direction: "vers BEC" },
    { avg: 4, hour: 13, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 13, type: "PL", direction: "vers BEC" },
    { avg: 112, hour: 13, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 14, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 14, type: "PL", direction: "vers BEC" },
    { avg: 81, hour: 14, type: "VL", direction: "vers BEC" },
    { avg: 4, hour: 15, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 15, type: "PL", direction: "vers BEC" },
    { avg: 106, hour: 15, type: "VL", direction: "vers BEC" },
    { avg: 5, hour: 16, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 16, type: "PL", direction: "vers BEC" },
    { avg: 189, hour: 16, type: "VL", direction: "vers BEC" },
    { avg: 5, hour: 17, type: "2R", direction: "vers BEC" },
    { avg: 4, hour: 17, type: "PL", direction: "vers BEC" },
    { avg: 222, hour: 17, type: "VL", direction: "vers BEC" },
    { avg: 6, hour: 18, type: "2R", direction: "vers BEC" },
    { avg: 4, hour: 18, type: "PL", direction: "vers BEC" },
    { avg: 200, hour: 18, type: "VL", direction: "vers BEC" },
    { avg: 7, hour: 19, type: "2R", direction: "vers BEC" },
    { avg: 3, hour: 19, type: "PL", direction: "vers BEC" },
    { avg: 130, hour: 19, type: "VL", direction: "vers BEC" },
    { avg: 4, hour: 20, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 20, type: "PL", direction: "vers BEC" },
    { avg: 79, hour: 20, type: "VL", direction: "vers BEC" },
    { avg: 3, hour: 21, type: "2R", direction: "vers BEC" },
    { avg: 2, hour: 21, type: "PL", direction: "vers BEC" },
    { avg: 48, hour: 21, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 22, type: "2R", direction: "vers BEC" },
    { avg: 1, hour: 22, type: "PL", direction: "vers BEC" },
    { avg: 38, hour: 22, type: "VL", direction: "vers BEC" },
    { avg: 1, hour: 23, type: "2R", direction: "vers BEC" },
    { avg: 1, hour: 23, type: "PL", direction: "vers BEC" },
    { avg: 25, hour: 23, type: "VL", direction: "vers BEC" },
    { avg: 2, hour: 0, type: "2R", direction: "vers COSEC" },
    { avg: 5, hour: 0, type: "PL", direction: "vers COSEC" },
    { avg: 9, hour: 0, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 1, type: "2R", direction: "vers COSEC" },
    { avg: 2, hour: 1, type: "PL", direction: "vers COSEC" },
    { avg: 6, hour: 1, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 2, type: "2R", direction: "vers COSEC" },
    { avg: 3, hour: 2, type: "PL", direction: "vers COSEC" },
    { avg: 3, hour: 2, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 3, type: "PL", direction: "vers COSEC" },
    { avg: 3, hour: 3, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 4, type: "2R", direction: "vers COSEC" },
    { avg: 2, hour: 4, type: "PL", direction: "vers COSEC" },
    { avg: 3, hour: 4, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 5, type: "2R", direction: "vers COSEC" },
    { avg: 1, hour: 5, type: "PL", direction: "vers COSEC" },
    { avg: 5, hour: 5, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 6, type: "2R", direction: "vers COSEC" },
    { avg: 6, hour: 6, type: "PL", direction: "vers COSEC" },
    { avg: 12, hour: 6, type: "VL", direction: "vers COSEC" },
    { avg: 5, hour: 7, type: "2R", direction: "vers COSEC" },
    { avg: 12, hour: 7, type: "PL", direction: "vers COSEC" },
    { avg: 41, hour: 7, type: "VL", direction: "vers COSEC" },
    { avg: 5, hour: 8, type: "2R", direction: "vers COSEC" },
    { avg: 14, hour: 8, type: "PL", direction: "vers COSEC" },
    { avg: 65, hour: 8, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 9, type: "2R", direction: "vers COSEC" },
    { avg: 15, hour: 9, type: "PL", direction: "vers COSEC" },
    { avg: 56, hour: 9, type: "VL", direction: "vers COSEC" },
    { avg: 2, hour: 10, type: "2R", direction: "vers COSEC" },
    { avg: 13, hour: 10, type: "PL", direction: "vers COSEC" },
    { avg: 45, hour: 10, type: "VL", direction: "vers COSEC" },
    { avg: 2, hour: 11, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 11, type: "PL", direction: "vers COSEC" },
    { avg: 48, hour: 11, type: "VL", direction: "vers COSEC" },
    { avg: 4, hour: 12, type: "2R", direction: "vers COSEC" },
    { avg: 11, hour: 12, type: "PL", direction: "vers COSEC" },
    { avg: 73, hour: 12, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 13, type: "2R", direction: "vers COSEC" },
    { avg: 13, hour: 13, type: "PL", direction: "vers COSEC" },
    { avg: 66, hour: 13, type: "VL", direction: "vers COSEC" },
    { avg: 2, hour: 14, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 14, type: "PL", direction: "vers COSEC" },
    { avg: 52, hour: 14, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 15, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 15, type: "PL", direction: "vers COSEC" },
    { avg: 60, hour: 15, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 16, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 16, type: "PL", direction: "vers COSEC" },
    { avg: 72, hour: 16, type: "VL", direction: "vers COSEC" },
    { avg: 5, hour: 17, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 17, type: "PL", direction: "vers COSEC" },
    { avg: 93, hour: 17, type: "VL", direction: "vers COSEC" },
    { avg: 5, hour: 18, type: "2R", direction: "vers COSEC" },
    { avg: 10, hour: 18, type: "PL", direction: "vers COSEC" },
    { avg: 88, hour: 18, type: "VL", direction: "vers COSEC" },
    { avg: 5, hour: 19, type: "2R", direction: "vers COSEC" },
    { avg: 8, hour: 19, type: "PL", direction: "vers COSEC" },
    { avg: 64, hour: 19, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 20, type: "2R", direction: "vers COSEC" },
    { avg: 7, hour: 20, type: "PL", direction: "vers COSEC" },
    { avg: 49, hour: 20, type: "VL", direction: "vers COSEC" },
    { avg: 3, hour: 21, type: "2R", direction: "vers COSEC" },
    { avg: 8, hour: 21, type: "PL", direction: "vers COSEC" },
    { avg: 28, hour: 21, type: "VL", direction: "vers COSEC" },
    { avg: 2, hour: 22, type: "2R", direction: "vers COSEC" },
    { avg: 6, hour: 22, type: "PL", direction: "vers COSEC" },
    { avg: 21, hour: 22, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 23, type: "2R", direction: "vers COSEC" },
    { avg: 3, hour: 23, type: "PL", direction: "vers COSEC" },
    { avg: 16, hour: 23, type: "VL", direction: "vers COSEC" },
    { avg: 1, hour: 0, type: "2R", direction: "vers CROUS" },
    { avg: 2, hour: 0, type: "PL", direction: "vers CROUS" },
    { avg: 28, hour: 0, type: "VL", direction: "vers CROUS" },
    { avg: 1, hour: 1, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 1, type: "PL", direction: "vers CROUS" },
    { avg: 15, hour: 1, type: "VL", direction: "vers CROUS" },
    { avg: 2, hour: 2, type: "2R", direction: "vers CROUS" },
    { avg: 3, hour: 2, type: "PL", direction: "vers CROUS" },
    { avg: 12, hour: 2, type: "VL", direction: "vers CROUS" },
    { avg: 1, hour: 3, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 3, type: "PL", direction: "vers CROUS" },
    { avg: 9, hour: 3, type: "VL", direction: "vers CROUS" },
    { avg: 1, hour: 4, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 4, type: "PL", direction: "vers CROUS" },
    { avg: 11, hour: 4, type: "VL", direction: "vers CROUS" },
    { avg: 2, hour: 5, type: "2R", direction: "vers CROUS" },
    { avg: 3, hour: 5, type: "PL", direction: "vers CROUS" },
    { avg: 22, hour: 5, type: "VL", direction: "vers CROUS" },
    { avg: 4, hour: 6, type: "2R", direction: "vers CROUS" },
    { avg: 4, hour: 6, type: "PL", direction: "vers CROUS" },
    { avg: 126, hour: 6, type: "VL", direction: "vers CROUS" },
    { avg: 23, hour: 7, type: "2R", direction: "vers CROUS" },
    { avg: 5, hour: 7, type: "PL", direction: "vers CROUS" },
    { avg: 274, hour: 7, type: "VL", direction: "vers CROUS" },
    { avg: 33, hour: 8, type: "2R", direction: "vers CROUS" },
    { avg: 7, hour: 8, type: "PL", direction: "vers CROUS" },
    { avg: 298, hour: 8, type: "VL", direction: "vers CROUS" },
    { avg: 17, hour: 9, type: "2R", direction: "vers CROUS" },
    { avg: 9, hour: 9, type: "PL", direction: "vers CROUS" },
    { avg: 267, hour: 9, type: "VL", direction: "vers CROUS" },
    { avg: 9, hour: 10, type: "2R", direction: "vers CROUS" },
    { avg: 5, hour: 10, type: "PL", direction: "vers CROUS" },
    { avg: 208, hour: 10, type: "VL", direction: "vers CROUS" },
    { avg: 10, hour: 11, type: "2R", direction: "vers CROUS" },
    { avg: 6, hour: 11, type: "PL", direction: "vers CROUS" },
    { avg: 184, hour: 11, type: "VL", direction: "vers CROUS" },
    { avg: 12, hour: 12, type: "2R", direction: "vers CROUS" },
    { avg: 4, hour: 12, type: "PL", direction: "vers CROUS" },
    { avg: 234, hour: 12, type: "VL", direction: "vers CROUS" },
    { avg: 16, hour: 13, type: "2R", direction: "vers CROUS" },
    { avg: 4, hour: 13, type: "PL", direction: "vers CROUS" },
    { avg: 244, hour: 13, type: "VL", direction: "vers CROUS" },
    { avg: 8, hour: 14, type: "2R", direction: "vers CROUS" },
    { avg: 4, hour: 14, type: "PL", direction: "vers CROUS" },
    { avg: 175, hour: 14, type: "VL", direction: "vers CROUS" },
    { avg: 12, hour: 15, type: "2R", direction: "vers CROUS" },
    { avg: 3, hour: 15, type: "PL", direction: "vers CROUS" },
    { avg: 184, hour: 15, type: "VL", direction: "vers CROUS" },
    { avg: 13, hour: 16, type: "2R", direction: "vers CROUS" },
    { avg: 3, hour: 16, type: "PL", direction: "vers CROUS" },
    { avg: 198, hour: 16, type: "VL", direction: "vers CROUS" },
    { avg: 20, hour: 17, type: "2R", direction: "vers CROUS" },
    { avg: 2, hour: 17, type: "PL", direction: "vers CROUS" },
    { avg: 245, hour: 17, type: "VL", direction: "vers CROUS" },
    { avg: 23, hour: 18, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 18, type: "PL", direction: "vers CROUS" },
    { avg: 253, hour: 18, type: "VL", direction: "vers CROUS" },
    { avg: 17, hour: 19, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 19, type: "PL", direction: "vers CROUS" },
    { avg: 206, hour: 19, type: "VL", direction: "vers CROUS" },
    { avg: 13, hour: 20, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 20, type: "PL", direction: "vers CROUS" },
    { avg: 147, hour: 20, type: "VL", direction: "vers CROUS" },
    { avg: 7, hour: 21, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 21, type: "PL", direction: "vers CROUS" },
    { avg: 85, hour: 21, type: "VL", direction: "vers CROUS" },
    { avg: 4, hour: 22, type: "2R", direction: "vers CROUS" },
    { avg: 1, hour: 22, type: "PL", direction: "vers CROUS" },
    { avg: 66, hour: 22, type: "VL", direction: "vers CROUS" },
    { avg: 2, hour: 23, type: "2R", direction: "vers CROUS" },
    { avg: 2, hour: 23, type: "PL", direction: "vers CROUS" },
    { avg: 46, hour: 23, type: "VL", direction: "vers CROUS" },
    { avg: 1, hour: 0, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 0, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 26, hour: 0, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 2, hour: 1, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 1, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 13, hour: 1, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 2, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 2, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 9, hour: 2, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 3, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 3, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 7, hour: 3, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 4, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 4, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 10, hour: 4, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 5, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 5, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 15, hour: 5, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 6, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 6, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 44, hour: 6, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 3, hour: 7, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 3, hour: 7, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 141, hour: 7, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 15, hour: 8, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 4, hour: 8, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 160, hour: 8, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 9, hour: 9, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 6, hour: 9, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 136, hour: 9, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 6, hour: 10, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 5, hour: 10, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 141,
        hour: 10,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 8, hour: 11, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 4, hour: 11, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 163,
        hour: 11,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 19, hour: 12, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 2, hour: 12, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 225,
        hour: 12,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 13, hour: 13, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 4, hour: 13, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 185,
        hour: 13,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 9, hour: 14, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 3, hour: 14, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 179,
        hour: 14,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 15, hour: 15, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 5, hour: 15, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 260,
        hour: 15,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 21, hour: 16, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 5, hour: 16, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 416,
        hour: 16,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 32, hour: 17, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 17, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 460,
        hour: 17,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 29, hour: 18, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 18, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 389,
        hour: 18,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 18, hour: 19, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 19, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 283,
        hour: 19,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 7, hour: 20, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 20, type: "PL", direction: "vers Cours de la Libération" },
    {
        avg: 148,
        hour: 20,
        type: "VL",
        direction: "vers Cours de la Libération",
    },
    { avg: 3, hour: 21, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 21, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 80, hour: 21, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 3, hour: 22, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 1, hour: 22, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 61, hour: 22, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 2, hour: 23, type: "2R", direction: "vers Cours de la Libération" },
    { avg: 3, hour: 23, type: "PL", direction: "vers Cours de la Libération" },
    { avg: 42, hour: 23, type: "VL", direction: "vers Cours de la Libération" },
    { avg: 9, hour: 0, type: "2R", direction: "vers Entrée Fac" },
    { avg: 7, hour: 0, type: "PL", direction: "vers Entrée Fac" },
    { avg: 430, hour: 0, type: "VL", direction: "vers Entrée Fac" },
    { avg: 22, hour: 1, type: "2R", direction: "vers Entrée Fac" },
    { avg: 18, hour: 1, type: "PL", direction: "vers Entrée Fac" },
    { avg: 837, hour: 1, type: "VL", direction: "vers Entrée Fac" },
    { avg: 18, hour: 2, type: "2R", direction: "vers Entrée Fac" },
    { avg: 8, hour: 2, type: "PL", direction: "vers Entrée Fac" },
    { avg: 323, hour: 2, type: "VL", direction: "vers Entrée Fac" },
    { avg: 25, hour: 3, type: "2R", direction: "vers Entrée Fac" },
    { avg: 12, hour: 3, type: "PL", direction: "vers Entrée Fac" },
    { avg: 625, hour: 3, type: "VL", direction: "vers Entrée Fac" },
    { avg: 36, hour: 4, type: "2R", direction: "vers Entrée Fac" },
    { avg: 8, hour: 4, type: "PL", direction: "vers Entrée Fac" },
    { avg: 547, hour: 4, type: "VL", direction: "vers Entrée Fac" },
    { avg: 16, hour: 5, type: "2R", direction: "vers Entrée Fac" },
    { avg: 10, hour: 5, type: "PL", direction: "vers Entrée Fac" },
    { avg: 332, hour: 5, type: "VL", direction: "vers Entrée Fac" },
    { avg: 45, hour: 6, type: "2R", direction: "vers Entrée Fac" },
    { avg: 17, hour: 6, type: "PL", direction: "vers Entrée Fac" },
    { avg: 852, hour: 6, type: "VL", direction: "vers Entrée Fac" },
    { avg: 71, hour: 7, type: "2R", direction: "vers Entrée Fac" },
    { avg: 16, hour: 7, type: "PL", direction: "vers Entrée Fac" },
    { avg: 763, hour: 7, type: "VL", direction: "vers Entrée Fac" },
    { avg: 120, hour: 8, type: "2R", direction: "vers Entrée Fac" },
    { avg: 24, hour: 8, type: "PL", direction: "vers Entrée Fac" },
    { avg: 1130, hour: 8, type: "VL", direction: "vers Entrée Fac" },
    { avg: 100, hour: 9, type: "2R", direction: "vers Entrée Fac" },
    { avg: 19, hour: 9, type: "PL", direction: "vers Entrée Fac" },
    { avg: 829, hour: 9, type: "VL", direction: "vers Entrée Fac" },
    { avg: 48, hour: 10, type: "2R", direction: "vers Entrée Fac" },
    { avg: 30, hour: 10, type: "PL", direction: "vers Entrée Fac" },
    { avg: 567, hour: 10, type: "VL", direction: "vers Entrée Fac" },
    { avg: 46, hour: 11, type: "2R", direction: "vers Entrée Fac" },
    { avg: 20, hour: 11, type: "PL", direction: "vers Entrée Fac" },
    { avg: 806, hour: 11, type: "VL", direction: "vers Entrée Fac" },
    { avg: 70, hour: 12, type: "2R", direction: "vers Entrée Fac" },
    { avg: 24, hour: 12, type: "PL", direction: "vers Entrée Fac" },
    { avg: 997, hour: 12, type: "VL", direction: "vers Entrée Fac" },
    { avg: 95, hour: 13, type: "2R", direction: "vers Entrée Fac" },
    { avg: 24, hour: 13, type: "PL", direction: "vers Entrée Fac" },
    { avg: 1109, hour: 13, type: "VL", direction: "vers Entrée Fac" },
    { avg: 47, hour: 14, type: "2R", direction: "vers Entrée Fac" },
    { avg: 15, hour: 14, type: "PL", direction: "vers Entrée Fac" },
    { avg: 725, hour: 14, type: "VL", direction: "vers Entrée Fac" },
    { avg: 54, hour: 15, type: "2R", direction: "vers Entrée Fac" },
    { avg: 32, hour: 15, type: "PL", direction: "vers Entrée Fac" },
    { avg: 1032, hour: 15, type: "VL", direction: "vers Entrée Fac" },
    { avg: 53, hour: 16, type: "2R", direction: "vers Entrée Fac" },
    { avg: 14, hour: 16, type: "PL", direction: "vers Entrée Fac" },
    { avg: 575, hour: 16, type: "VL", direction: "vers Entrée Fac" },
    { avg: 78, hour: 17, type: "2R", direction: "vers Entrée Fac" },
    { avg: 22, hour: 17, type: "PL", direction: "vers Entrée Fac" },
    { avg: 870, hour: 17, type: "VL", direction: "vers Entrée Fac" },
    { avg: 82, hour: 18, type: "2R", direction: "vers Entrée Fac" },
    { avg: 25, hour: 18, type: "PL", direction: "vers Entrée Fac" },
    { avg: 879, hour: 18, type: "VL", direction: "vers Entrée Fac" },
    { avg: 43, hour: 19, type: "2R", direction: "vers Entrée Fac" },
    { avg: 14, hour: 19, type: "PL", direction: "vers Entrée Fac" },
    { avg: 508, hour: 19, type: "VL", direction: "vers Entrée Fac" },
    { avg: 43, hour: 20, type: "2R", direction: "vers Entrée Fac" },
    { avg: 19, hour: 20, type: "PL", direction: "vers Entrée Fac" },
    { avg: 942, hour: 20, type: "VL", direction: "vers Entrée Fac" },
    { avg: 21, hour: 21, type: "2R", direction: "vers Entrée Fac" },
    { avg: 10, hour: 21, type: "PL", direction: "vers Entrée Fac" },
    { avg: 317, hour: 21, type: "VL", direction: "vers Entrée Fac" },
    { avg: 22, hour: 22, type: "2R", direction: "vers Entrée Fac" },
    { avg: 12, hour: 22, type: "PL", direction: "vers Entrée Fac" },
    { avg: 611, hour: 22, type: "VL", direction: "vers Entrée Fac" },
    { avg: 14, hour: 23, type: "2R", direction: "vers Entrée Fac" },
    { avg: 15, hour: 23, type: "PL", direction: "vers Entrée Fac" },
    { avg: 550, hour: 23, type: "VL", direction: "vers Entrée Fac" },
    { avg: 2, hour: 0, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 0, type: "PL", direction: "vers Rocade" },
    { avg: 29, hour: 0, type: "VL", direction: "vers Rocade" },
    { avg: 1, hour: 1, type: "2R", direction: "vers Rocade" },
    { avg: 17, hour: 1, type: "VL", direction: "vers Rocade" },
    { avg: 1, hour: 2, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 2, type: "PL", direction: "vers Rocade" },
    { avg: 11, hour: 2, type: "VL", direction: "vers Rocade" },
    { avg: 1, hour: 3, type: "2R", direction: "vers Rocade" },
    { avg: 6, hour: 3, type: "VL", direction: "vers Rocade" },
    { avg: 1, hour: 4, type: "2R", direction: "vers Rocade" },
    { avg: 6, hour: 4, type: "VL", direction: "vers Rocade" },
    { avg: 1, hour: 5, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 5, type: "PL", direction: "vers Rocade" },
    { avg: 9, hour: 5, type: "VL", direction: "vers Rocade" },
    { avg: 2, hour: 6, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 6, type: "PL", direction: "vers Rocade" },
    { avg: 24, hour: 6, type: "VL", direction: "vers Rocade" },
    { avg: 10, hour: 7, type: "2R", direction: "vers Rocade" },
    { avg: 2, hour: 7, type: "PL", direction: "vers Rocade" },
    { avg: 175, hour: 7, type: "VL", direction: "vers Rocade" },
    { avg: 16, hour: 8, type: "2R", direction: "vers Rocade" },
    { avg: 2, hour: 8, type: "PL", direction: "vers Rocade" },
    { avg: 238, hour: 8, type: "VL", direction: "vers Rocade" },
    { avg: 8, hour: 9, type: "2R", direction: "vers Rocade" },
    { avg: 2, hour: 9, type: "PL", direction: "vers Rocade" },
    { avg: 142, hour: 9, type: "VL", direction: "vers Rocade" },
    { avg: 6, hour: 10, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 10, type: "PL", direction: "vers Rocade" },
    { avg: 108, hour: 10, type: "VL", direction: "vers Rocade" },
    { avg: 4, hour: 11, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 11, type: "PL", direction: "vers Rocade" },
    { avg: 135, hour: 11, type: "VL", direction: "vers Rocade" },
    { avg: 12, hour: 12, type: "2R", direction: "vers Rocade" },
    { avg: 2, hour: 12, type: "PL", direction: "vers Rocade" },
    { avg: 206, hour: 12, type: "VL", direction: "vers Rocade" },
    { avg: 14, hour: 13, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 13, type: "PL", direction: "vers Rocade" },
    { avg: 228, hour: 13, type: "VL", direction: "vers Rocade" },
    { avg: 7, hour: 14, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 14, type: "PL", direction: "vers Rocade" },
    { avg: 154, hour: 14, type: "VL", direction: "vers Rocade" },
    { avg: 8, hour: 15, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 15, type: "PL", direction: "vers Rocade" },
    { avg: 191, hour: 15, type: "VL", direction: "vers Rocade" },
    { avg: 12, hour: 16, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 16, type: "PL", direction: "vers Rocade" },
    { avg: 263, hour: 16, type: "VL", direction: "vers Rocade" },
    { avg: 16, hour: 17, type: "2R", direction: "vers Rocade" },
    { avg: 2, hour: 17, type: "PL", direction: "vers Rocade" },
    { avg: 337, hour: 17, type: "VL", direction: "vers Rocade" },
    { avg: 14, hour: 18, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 18, type: "PL", direction: "vers Rocade" },
    { avg: 299, hour: 18, type: "VL", direction: "vers Rocade" },
    { avg: 13, hour: 19, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 19, type: "PL", direction: "vers Rocade" },
    { avg: 189, hour: 19, type: "VL", direction: "vers Rocade" },
    { avg: 10, hour: 20, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 20, type: "PL", direction: "vers Rocade" },
    { avg: 118, hour: 20, type: "VL", direction: "vers Rocade" },
    { avg: 7, hour: 21, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 21, type: "PL", direction: "vers Rocade" },
    { avg: 67, hour: 21, type: "VL", direction: "vers Rocade" },
    { avg: 5, hour: 22, type: "2R", direction: "vers Rocade" },
    { avg: 62, hour: 22, type: "VL", direction: "vers Rocade" },
    { avg: 3, hour: 23, type: "2R", direction: "vers Rocade" },
    { avg: 1, hour: 23, type: "PL", direction: "vers Rocade" },
    { avg: 47, hour: 23, type: "VL", direction: "vers Rocade" },
    { avg: 8, hour: 0, type: "2R", direction: "vers Sortie Fac" },
    { avg: 2, hour: 0, type: "PL", direction: "vers Sortie Fac" },
    { avg: 224, hour: 0, type: "VL", direction: "vers Sortie Fac" },
    { avg: 15, hour: 1, type: "2R", direction: "vers Sortie Fac" },
    { avg: 2, hour: 1, type: "PL", direction: "vers Sortie Fac" },
    { avg: 433, hour: 1, type: "VL", direction: "vers Sortie Fac" },
    { avg: 7, hour: 2, type: "2R", direction: "vers Sortie Fac" },
    { avg: 2, hour: 2, type: "PL", direction: "vers Sortie Fac" },
    { avg: 197, hour: 2, type: "VL", direction: "vers Sortie Fac" },
    { avg: 15, hour: 3, type: "2R", direction: "vers Sortie Fac" },
    { avg: 3, hour: 3, type: "PL", direction: "vers Sortie Fac" },
    { avg: 379, hour: 3, type: "VL", direction: "vers Sortie Fac" },
    { avg: 19, hour: 4, type: "2R", direction: "vers Sortie Fac" },
    { avg: 3, hour: 4, type: "PL", direction: "vers Sortie Fac" },
    { avg: 378, hour: 4, type: "VL", direction: "vers Sortie Fac" },
    { avg: 10, hour: 5, type: "2R", direction: "vers Sortie Fac" },
    { avg: 4, hour: 5, type: "PL", direction: "vers Sortie Fac" },
    { avg: 237, hour: 5, type: "VL", direction: "vers Sortie Fac" },
    { avg: 29, hour: 6, type: "2R", direction: "vers Sortie Fac" },
    { avg: 5, hour: 6, type: "PL", direction: "vers Sortie Fac" },
    { avg: 637, hour: 6, type: "VL", direction: "vers Sortie Fac" },
    { avg: 12, hour: 7, type: "2R", direction: "vers Sortie Fac" },
    { avg: 5, hour: 7, type: "PL", direction: "vers Sortie Fac" },
    { avg: 298, hour: 7, type: "VL", direction: "vers Sortie Fac" },
    { avg: 26, hour: 8, type: "2R", direction: "vers Sortie Fac" },
    { avg: 7, hour: 8, type: "PL", direction: "vers Sortie Fac" },
    { avg: 439, hour: 8, type: "VL", direction: "vers Sortie Fac" },
    { avg: 21, hour: 9, type: "2R", direction: "vers Sortie Fac" },
    { avg: 6, hour: 9, type: "PL", direction: "vers Sortie Fac" },
    { avg: 420, hour: 9, type: "VL", direction: "vers Sortie Fac" },
    { avg: 23, hour: 10, type: "2R", direction: "vers Sortie Fac" },
    { avg: 7, hour: 10, type: "PL", direction: "vers Sortie Fac" },
    { avg: 462, hour: 10, type: "VL", direction: "vers Sortie Fac" },
    { avg: 33, hour: 11, type: "2R", direction: "vers Sortie Fac" },
    { avg: 9, hour: 11, type: "PL", direction: "vers Sortie Fac" },
    { avg: 528, hour: 11, type: "VL", direction: "vers Sortie Fac" },
    { avg: 62, hour: 12, type: "2R", direction: "vers Sortie Fac" },
    { avg: 6, hour: 12, type: "PL", direction: "vers Sortie Fac" },
    { avg: 631, hour: 12, type: "VL", direction: "vers Sortie Fac" },
    { avg: 42, hour: 13, type: "2R", direction: "vers Sortie Fac" },
    { avg: 7, hour: 13, type: "PL", direction: "vers Sortie Fac" },
    { avg: 648, hour: 13, type: "VL", direction: "vers Sortie Fac" },
    { avg: 31, hour: 14, type: "2R", direction: "vers Sortie Fac" },
    { avg: 5, hour: 14, type: "PL", direction: "vers Sortie Fac" },
    { avg: 469, hour: 14, type: "VL", direction: "vers Sortie Fac" },
    { avg: 50, hour: 15, type: "2R", direction: "vers Sortie Fac" },
    { avg: 8, hour: 15, type: "PL", direction: "vers Sortie Fac" },
    { avg: 710, hour: 15, type: "VL", direction: "vers Sortie Fac" },
    { avg: 57, hour: 16, type: "2R", direction: "vers Sortie Fac" },
    { avg: 4, hour: 16, type: "PL", direction: "vers Sortie Fac" },
    { avg: 463, hour: 16, type: "VL", direction: "vers Sortie Fac" },
    { avg: 97, hour: 17, type: "2R", direction: "vers Sortie Fac" },
    { avg: 5, hour: 17, type: "PL", direction: "vers Sortie Fac" },
    { avg: 604, hour: 17, type: "VL", direction: "vers Sortie Fac" },
    { avg: 92, hour: 18, type: "2R", direction: "vers Sortie Fac" },
    { avg: 4, hour: 18, type: "PL", direction: "vers Sortie Fac" },
    { avg: 599, hour: 18, type: "VL", direction: "vers Sortie Fac" },
    { avg: 50, hour: 19, type: "2R", direction: "vers Sortie Fac" },
    { avg: 3, hour: 19, type: "PL", direction: "vers Sortie Fac" },
    { avg: 379, hour: 19, type: "VL", direction: "vers Sortie Fac" },
    { avg: 47, hour: 20, type: "2R", direction: "vers Sortie Fac" },
    { avg: 4, hour: 20, type: "PL", direction: "vers Sortie Fac" },
    { avg: 649, hour: 20, type: "VL", direction: "vers Sortie Fac" },
    { avg: 18, hour: 21, type: "2R", direction: "vers Sortie Fac" },
    { avg: 2, hour: 21, type: "PL", direction: "vers Sortie Fac" },
    { avg: 271, hour: 21, type: "VL", direction: "vers Sortie Fac" },
    { avg: 22, hour: 22, type: "2R", direction: "vers Sortie Fac" },
    { avg: 4, hour: 22, type: "PL", direction: "vers Sortie Fac" },
    { avg: 407, hour: 22, type: "VL", direction: "vers Sortie Fac" },
    { avg: 12, hour: 23, type: "2R", direction: "vers Sortie Fac" },
    { avg: 3, hour: 23, type: "PL", direction: "vers Sortie Fac" },
    { avg: 320, hour: 23, type: "VL", direction: "vers Sortie Fac" },
    { avg: 1, hour: 0, type: "2R", direction: "vers Talence" },
    { avg: 9, hour: 0, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 1, type: "2R", direction: "vers Talence" },
    { avg: 4, hour: 1, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 2, type: "2R", direction: "vers Talence" },
    { avg: 4, hour: 2, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 3, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 3, type: "PL", direction: "vers Talence" },
    { avg: 2, hour: 3, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 4, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 4, type: "PL", direction: "vers Talence" },
    { avg: 1, hour: 4, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 5, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 5, type: "PL", direction: "vers Talence" },
    { avg: 4, hour: 5, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 6, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 6, type: "PL", direction: "vers Talence" },
    { avg: 12, hour: 6, type: "VL", direction: "vers Talence" },
    { avg: 3, hour: 7, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 7, type: "PL", direction: "vers Talence" },
    { avg: 66, hour: 7, type: "VL", direction: "vers Talence" },
    { avg: 4, hour: 8, type: "2R", direction: "vers Talence" },
    { avg: 2, hour: 8, type: "PL", direction: "vers Talence" },
    { avg: 104, hour: 8, type: "VL", direction: "vers Talence" },
    { avg: 2, hour: 9, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 9, type: "PL", direction: "vers Talence" },
    { avg: 73, hour: 9, type: "VL", direction: "vers Talence" },
    { avg: 2, hour: 10, type: "2R", direction: "vers Talence" },
    { avg: 2, hour: 10, type: "PL", direction: "vers Talence" },
    { avg: 63, hour: 10, type: "VL", direction: "vers Talence" },
    { avg: 3, hour: 11, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 11, type: "PL", direction: "vers Talence" },
    { avg: 86, hour: 11, type: "VL", direction: "vers Talence" },
    { avg: 7, hour: 12, type: "2R", direction: "vers Talence" },
    { avg: 2, hour: 12, type: "PL", direction: "vers Talence" },
    { avg: 135, hour: 12, type: "VL", direction: "vers Talence" },
    { avg: 6, hour: 13, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 13, type: "PL", direction: "vers Talence" },
    { avg: 93, hour: 13, type: "VL", direction: "vers Talence" },
    { avg: 4, hour: 14, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 14, type: "PL", direction: "vers Talence" },
    { avg: 79, hour: 14, type: "VL", direction: "vers Talence" },
    { avg: 5, hour: 15, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 15, type: "PL", direction: "vers Talence" },
    { avg: 94, hour: 15, type: "VL", direction: "vers Talence" },
    { avg: 8, hour: 16, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 16, type: "PL", direction: "vers Talence" },
    { avg: 158, hour: 16, type: "VL", direction: "vers Talence" },
    { avg: 16, hour: 17, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 17, type: "PL", direction: "vers Talence" },
    { avg: 191, hour: 17, type: "VL", direction: "vers Talence" },
    { avg: 15, hour: 18, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 18, type: "PL", direction: "vers Talence" },
    { avg: 188, hour: 18, type: "VL", direction: "vers Talence" },
    { avg: 8, hour: 19, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 19, type: "PL", direction: "vers Talence" },
    { avg: 133, hour: 19, type: "VL", direction: "vers Talence" },
    { avg: 7, hour: 20, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 20, type: "PL", direction: "vers Talence" },
    { avg: 77, hour: 20, type: "VL", direction: "vers Talence" },
    { avg: 5, hour: 21, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 21, type: "PL", direction: "vers Talence" },
    { avg: 35, hour: 21, type: "VL", direction: "vers Talence" },
    { avg: 3, hour: 22, type: "2R", direction: "vers Talence" },
    { avg: 1, hour: 22, type: "PL", direction: "vers Talence" },
    { avg: 25, hour: 22, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 23, type: "2R", direction: "vers Talence" },
    { avg: 17, hour: 23, type: "VL", direction: "vers Talence" },
    { avg: 1, hour: 0, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 0, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 1, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 2, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 2, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 3, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 4, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 4, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 5, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 5, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 6, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 2, hour: 6, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 8, hour: 7, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 7, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 43, hour: 7, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 6, hour: 8, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 8, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 29, hour: 8, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 10, hour: 9, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 9, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 45, hour: 9, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 2, hour: 10, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 10, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 18, hour: 10, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 6, hour: 11, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 11, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 34, hour: 11, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 3, hour: 12, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 12, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 29, hour: 12, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 6, hour: 13, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 30, hour: 13, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 6, hour: 14, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 14, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 29, hour: 14, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 2, hour: 15, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 12, hour: 15, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 5, hour: 16, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 25, hour: 16, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 3, hour: 17, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 15, hour: 17, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 3, hour: 18, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 24, hour: 18, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 19, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 2, hour: 19, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 11, hour: 19, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 20, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 20, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 4, hour: 20, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 21, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 2, hour: 21, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 22, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 22, type: "PL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 22, type: "VL", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 23, type: "2R", direction: "vers avenue Léon Duguit" },
    { avg: 1, hour: 23, type: "VL", direction: "vers avenue Léon Duguit" },
    {
        avg: 2,
        hour: 0,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 10,
        hour: 0,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 1,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 7,
        hour: 1,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 2,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 2,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 6,
        hour: 2,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 3,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 3,
        hour: 3,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 4,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 4,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 3,
        hour: 4,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 5,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 4,
        hour: 5,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 6,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 6,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 27,
        hour: 6,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 7,
        hour: 7,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 3,
        hour: 7,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 73,
        hour: 7,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 13,
        hour: 8,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 8,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 99,
        hour: 8,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 8,
        hour: 9,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 9,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 63,
        hour: 9,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 4,
        hour: 10,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 10,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 49,
        hour: 10,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 5,
        hour: 11,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 11,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 50,
        hour: 11,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 12,
        hour: 12,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 12,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 97,
        hour: 12,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 7,
        hour: 13,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 13,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 67,
        hour: 13,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 5,
        hour: 14,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 53,
        hour: 14,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 7,
        hour: 15,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 15,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 56,
        hour: 15,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 12,
        hour: 16,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 16,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 77,
        hour: 16,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 19,
        hour: 17,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 117,
        hour: 17,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 17,
        hour: 18,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 18,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 116,
        hour: 18,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 12,
        hour: 19,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 19,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 72,
        hour: 19,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 9,
        hour: 20,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 49,
        hour: 20,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 6,
        hour: 21,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 32,
        hour: 21,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 3,
        hour: 22,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 27,
        hour: 22,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 2,
        hour: 23,
        type: "2R",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 1,
        hour: 23,
        type: "PL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    {
        avg: 18,
        hour: 23,
        type: "VL",
        direction: "vers carrefour é feux Av. Roul ",
    },
    { avg: 1, hour: 0, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 3, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 5, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 5, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 6, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 6, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 7, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 7, type: "PL", direction: "vers parking cafeteria" },
    { avg: 2, hour: 7, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 8, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 8, type: "PL", direction: "vers parking cafeteria" },
    { avg: 2, hour: 8, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 9, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 9, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 9, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 10, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 10, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 11, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 11, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 11, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 12, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 12, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 13, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 13, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 13, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 14, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 14, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 15, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 15, type: "PL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 15, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 16, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 16, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 17, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 18, type: "2R", direction: "vers parking cafeteria" },
    { avg: 1, hour: 18, type: "VL", direction: "vers parking cafeteria" },
    { avg: 2, hour: 19, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 20, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 22, type: "VL", direction: "vers parking cafeteria" },
    { avg: 1, hour: 6, type: "PL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 6, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 7, type: "2R", direction: "vers parking des professeurs" },
    { avg: 1, hour: 7, type: "PL", direction: "vers parking des professeurs" },
    { avg: 2, hour: 7, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 8, type: "2R", direction: "vers parking des professeurs" },
    { avg: 1, hour: 8, type: "PL", direction: "vers parking des professeurs" },
    { avg: 9, hour: 8, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 9, type: "2R", direction: "vers parking des professeurs" },
    { avg: 6, hour: 9, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 10, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 11, type: "2R", direction: "vers parking des professeurs" },
    { avg: 2, hour: 11, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 12, type: "PL", direction: "vers parking des professeurs" },
    { avg: 2, hour: 12, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 13, type: "2R", direction: "vers parking des professeurs" },
    { avg: 3, hour: 13, type: "VL", direction: "vers parking des professeurs" },
    { avg: 2, hour: 14, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 15, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 16, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 18, type: "PL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 18, type: "VL", direction: "vers parking des professeurs" },
    { avg: 1, hour: 20, type: "VL", direction: "vers parking des professeurs" },
];

export const getAverageTrafficByHour = () => {
    return trafficData;
};

export const getAverageByDirection = (direction: string) => {
    return trafficData.filter((data) => data.direction === direction);
};

export const getAverageTrafficByHourAndDirection = (direction: string) => {
    return trafficData.filter((data) => data.direction === direction);
};

export const getAverageTrafficByHourAndDirectionAndType = (
    direction: string,
    type: string
) => {
    return trafficData.filter(
        (data) => data.direction === direction && data.type === type
    );
};

const getPLInHour = (hour: number, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.hour === hour &&
            data.type === "PL" &&
            data.direction === direction
    )[0]?.avg;
};

const getVLInHour = (hour: number, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.hour === hour &&
            data.type === "VL" &&
            data.direction === direction
    )[0]?.avg;
};

const get2RInHour = (hour: number, direction: string) => {
    return trafficData.filter(
        (data) =>
            data.hour === hour &&
            data.type === "2R" &&
            data.direction === direction
    )[0]?.avg;
};

export const reduceByDirection = () => {
    const directions = trafficData.map((data) => data.direction);
    const setDirections = new Set(directions);
    const uniqueDirections = Array.from(setDirections);
    const reducedData = uniqueDirections.map((direction: any) => {
        const data = getAverageByDirection(direction);
        return {
            direction: direction,
            values: removeDuplications(
                data.map((data) => {
                    return {
                        hour: data.hour,
                        avgPL: getPLInHour(data.hour, direction),
                        avgVL: getVLInHour(data.hour, direction),
                        avg2R: get2RInHour(data.hour, direction),
                    };
                })
            ),
        };
    });
    return reducedData;
};

export const getDataByDirection = (direction: string) => {
    return reduceByDirection().filter(
        (data) => data.direction === direction
    )[0];
};

const removeDuplications = (
    array: {
        hour: number;
        avgPL: number;
        avgVL: number;
        avg2R: number;
    }[]
) => {
    return array.filter(
        (thing: any, index, self) =>
            index ===
            self.findIndex(
                (t) =>
                    t.hour === thing.hour &&
                    t.avgPL === thing.avgPL &&
                    t.avgVL === thing.avgVL &&
                    t.avg2R === thing.avg2R
            )
    );
};

export const getAllDirections = () => {
    const directions = trafficData.map((data) => data.direction);
    const setDirections = new Set(directions);
    const uniqueDirections = Array.from(setDirections);
    return uniqueDirections;
};
